# Generated by Django 3.0.5 on 2021-01-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('other_names', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('mobile_num', models.CharField(max_length=100)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('vote', models.CharField(max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote', to='voting.User')),
            ],
        ),
    ]
