# Generated by Django 3.0.5 on 2021-01-14 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20210114_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='otp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
