# Generated by Django 3.0.5 on 2021-01-14 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20210114_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unregistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unregistered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
