# Generated by Django 3.0.5 on 2021-01-14 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_unregistered'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.ManyToManyField(related_name='candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unregistered',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unregistered', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
