# Generated by Django 3.0.5 on 2021-01-22 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20210114_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregistered',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unregistered', to=settings.AUTH_USER_MODEL),
        ),
    ]
